version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  auto: artsy/auto@1.2.1

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/lint:
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/lint
            - yarn/type-check
            - yarn/update-cache
